/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const OnboardingEntry = IDL.Record({
  'schoolSize' : IDL.Text,
  'contactName' : IDL.Text,
  'role' : IDL.Text,
  'contactEmail' : IDL.Text,
  'contactPhone' : IDL.Text,
  'schoolName' : IDL.Text,
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });

export const idlService = IDL.Service({
  'getAllOnboardings' : IDL.Func([], [IDL.Vec(OnboardingEntry)], ['query']),
  'getOnboardingCount' : IDL.Func([], [IDL.Nat], ['query']),
  'submitOnboarding' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Result],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const OnboardingEntry = IDL.Record({
    'schoolSize' : IDL.Text,
    'contactName' : IDL.Text,
    'role' : IDL.Text,
    'contactEmail' : IDL.Text,
    'contactPhone' : IDL.Text,
    'schoolName' : IDL.Text,
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  
  return IDL.Service({
    'getAllOnboardings' : IDL.Func([], [IDL.Vec(OnboardingEntry)], ['query']),
    'getOnboardingCount' : IDL.Func([], [IDL.Nat], ['query']),
    'submitOnboarding' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Result],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };