/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface OnboardingEntry {
  'schoolSize' : string,
  'contactName' : string,
  'role' : string,
  'contactEmail' : string,
  'contactPhone' : string,
  'schoolName' : string,
}
export type Result = { 'ok' : null } |
  { 'err' : string };
export interface _SERVICE {
  'getAllOnboardings' : ActorMethod<[], Array<OnboardingEntry>>,
  'getOnboardingCount' : ActorMethod<[], bigint>,
  'submitOnboarding' : ActorMethod<
    [string, string, string, string, string, string],
    Result
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];